api_platform:
    title: Talkly API Platform
    version: 1.0.0
    mapping: 
         paths: ['%kernel.project_dir%/src/Entity']
    enable_swagger_ui: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
