<?php

namespace App\DataFixtures;

use App\Entity\Cards;
use App\Entity\Category;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;

class CardFixtures extends Fixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager): void
    {
        // Categories mapped to card questions
        $cards = [
            'icebreakers' => [
                "What's your favorite season and why?",
                "If you could have dinner with any famous person, who would it be?",
                "What’s the last movie you watched?",
                "Do you prefer the beach or the mountains?",
                "What’s your go-to karaoke song?",
                "Coffee or tea — and how do you take it?",
                "What's your most-used emoji?",
                "If you won a free plane ticket, where would you go?",
                "Morning person or night owl?",
                "What’s something people often misunderstand about you?",
                "If you had to eat one food for a week, what would it be?",
                "What’s your biggest irrational fear?",
                "What's your favorite app on your phone?",
                "Do you prefer cats, dogs, or something else?",
                "What’s the first thing you do when you wake up?",
                "What’s one thing you’d bring to a desert island?",
                "What’s a skill you wish you had?",
                "Would you rather explore space or the deep sea?",
                "What was your first job?",
                "What’s something that always makes you smile?",
            ],
            'would_you_rather' => [
                "Be able to fly or be invisible?",
                "Give up your phone or your pet for a week?",
                "Always be 10 minutes early or 20 minutes late?",
                "Never use social media again or never watch TV again?",
                "Live in the city or the countryside?",
                "Lose the ability to speak or the ability to read?",
                "Be rich and unknown or famous and broke?",
                "Have unlimited time or unlimited money?",
                "Always have to sing instead of speak or dance everywhere you go?",
                "Only be able to whisper or shout?",
                "Be stuck in a rom-com or a horror movie?",
                "Travel to the past or the future?",
                "Eat only sweet food or only salty food?",
                "Work 4 days a week for 10 hours or 6 days a week for 6 hours?",
                "Live without music or without movies?",
                "Always have to tell the truth or always lie?",
                "Only be able to text or only be able to call?",
                "Have a pause button or a rewind button in life?",
                "Be a famous chef or a world-class musician?",
                "Be able to speak all languages or play every instrument?",
            ],
            'deep_thoughts' => [
                "What does success mean to you?",
                "What’s something you’ve changed your mind about recently?",
                "If you could send a message to your younger self, what would it say?",
                "Do you believe everything happens for a reason?",
                "What’s the most important lesson life has taught you?",
                "When do you feel most at peace?",
                "How do you handle failure?",
                "What legacy do you want to leave behind?",
                "What does happiness look like to you?",
                "How do you define love?",
                "What role does fear play in your life?",
                "What’s a memory you hope to never forget?",
                "Do you believe people can truly change?",
                "What’s more important: truth or kindness?",
                "When was the last time you felt truly understood?",
                "What does freedom mean to you?",
                "How do you recharge after a long day?",
                "If you could master any virtue, which one would it be?",
                "Is it more important to be liked or respected?",
                "How do you know when you’re doing the right thing?",
            ],
            'pop_culture' => [
                "Who’s your favorite music artist right now?",
                "What TV show are you binge-watching?",
                "Marvel or DC — and why?",
                "What’s your favorite movie of all time?",
                "Who’s the most iconic celebrity in your opinion?",
                "What’s the last concert or live event you attended?",
                "What book deserves a movie adaptation?",
                "TikTok or Instagram — which do you prefer?",
                "If you could star in any movie genre, what would it be?",
                "What’s your guilty pleasure song?",
                "Who’s a fictional character you relate to?",
                "What’s one trend you don’t understand?",
                "Which celebrity would you swap lives with for a day?",
                "What’s a classic movie you’ve never seen?",
                "Which game show would you crush?",
                "If your life were a TV series, what would it be called?",
                "Who's your favorite late-night host?",
                "What’s a viral moment you still think about?",
                "What’s your favorite childhood cartoon?",
                "What’s a song that always gets you dancing?",
            ],
            'just_for_fun' => [
                "If animals could talk, which would be the rudest?",
                "What would your superhero name be?",
                "If you had a time machine, where’s the first place you’d go?",
                "What’s your weirdest talent?",
                "You find a genie — what’s your first wish?",
                "What’s something you could teach a class about?",
                "What’s your zombie apocalypse plan?",
                "Would you survive a day as your pet?",
                "If your life had a theme song, what would it be?",
                "What's the silliest fear you've ever had?",
                "Which cartoon world would you live in?",
                "What’s your dream job if money didn’t matter?",
                "What’s the worst fashion trend you ever followed?",
                "What would be your entrance song in a wrestling match?",
                "If you had to swap lives with a cartoon character, who?",
                "What would you name your spaceship?",
                "If you were invisible for a day, what would you do?",
                "What’s something totally useless you know a lot about?",
                "What’s the most ridiculous goal you've ever set?",
                "If you were a dessert, what would you be?",
            ],
            "music" => [
                "What’s a song that never fails to lift your mood?",
                "Which artist or band changed the way you think about music?",
                "What was the first concert you ever attended?",
                "Do you prefer listening to music with lyrics or instrumental?",
                "What’s your guilty pleasure song?",
                "Which music genre do you connect with most and why?",
                "If you could see any artist live, who would it be?",
                "Do you play any instruments?",
                "What's your go-to playlist for focus or work?",
                "Which soundtrack from a movie or game moved you the most?",
                "Do you prefer vinyl, digital, or live performances?",
                "What song reminds you of your childhood?",
                "Have you ever written or composed music?",
                "What’s your favorite karaoke song?",
                "Which decade had the best music, in your opinion?",
                "Do you follow any music charts or trends?",
                "What makes a great live performance?",
                "How do you discover new music?",
                "What’s a lyric that has stuck with you?",
                "Would you rather go to a music festival or a solo show?",
            ],
            "movies" => [
                "What’s a movie you can watch over and over?",
                "Who is your favorite film director and why?",
                "What movie has had the biggest emotional impact on you?",
                "Do you prefer watching movies at home or in the theater?",
                "What’s the most visually stunning film you’ve seen?",
                "Which film do you think is overrated?",
                "What’s your favorite film quote?",
                "Which genre do you avoid, and why?",
                "Who’s an actor or actress you’ll watch in anything?",
                "What’s your all-time favorite animated film?",
                "What movie scared you the most?",
                "Have you ever walked out of a theater? Why?",
                "What movie twist left you speechless?",
                "Which film soundtrack stands out the most to you?",
                "What’s your comfort movie?",
                "What’s one movie everyone should see at least once?",
                "Do you prefer fiction or documentaries?",
                "Which international film would you recommend?",
                "What movie has the best cinematography in your opinion?",
                "Have you ever cried during a movie? Which one?",
            ],
            "books" => [
                "What’s the last book you couldn’t put down?",
                "Which fictional world would you love to live in?",
                "Do you prefer physical books or e-books?",
                "Who’s your favorite author and why?",
                "What book changed your perspective on something important?",
                "Which genre do you read the most?",
                "Have you ever written a story or wanted to?",
                "What book do you always recommend to others?",
                "What’s a book you think is underrated?",
                "Do you enjoy audiobooks?",
                "Which book character do you relate to the most?",
                "Have you ever read a book in one sitting?",
                "What’s a classic book you think everyone should read?",
                "What’s your favorite childhood book?",
                "Do you keep a reading list or reading goal?",
                "What’s the most thought-provoking book you’ve read?",
                "Do you judge books by their covers?",
                "How do you discover new books?",
                "Is there a book you wish you could read again for the first time?",
                "Do you prefer standalone books or series?",
            ],
            "travel" => [
                "What’s the most memorable trip you’ve ever taken?",
                "Do you prefer nature destinations or cities?",
                "What’s one travel destination still on your bucket list?",
                "What’s your favorite thing about traveling?",
                "Have you ever had a travel disaster? What happened?",
                "Which country has the best food, in your opinion?",
                "What’s the best place to travel on a budget?",
                "Do you prefer solo travel or group trips?",
                "What’s the most beautiful place you've ever seen?",
                "Which cultural experience left a lasting impression on you?",
                "Do you collect souvenirs or travel journals?",
                "What’s your must-have item when you travel?",
                "What’s the longest trip you’ve ever taken?",
                "Which local dish surprised you the most while traveling?",
                "Do you like planning ahead or traveling spontaneously?",
                "What’s your favorite mode of travel (car, train, plane, etc.)?",
                "What travel advice would you give your younger self?",
                "What’s the most unique accommodation you’ve stayed in?",
                "Have you ever learned a new language for a trip?",
                "Would you rather revisit a favorite place or explore somewhere new?",
            ],
            "food" => [
                "What’s your ultimate comfort food?",
                "Do you prefer sweet or savory dishes?",
                "Which cuisine would you eat for the rest of your life?",
                "What’s a food you used to hate but now love?",
                "Have you ever tried cooking a dish from another culture?",
                "What’s your signature dish?",
                "What’s your go-to order at your favorite restaurant?",
                "Do you enjoy cooking or prefer eating out?",
                "What’s a food trend you never understood?",
                "What's the most exotic food you've ever tried?",
                "Do you prefer home-cooked meals or gourmet dining?",
                "What’s one dish you’d love to learn how to make?",
                "What’s your favorite food-related memory?",
                "What’s a snack you always keep around?",
                "Do you believe in following recipes or improvising?",
                "What food could you eat every day and never get tired of?",
                "What’s your favorite seasonal dish?",
                "Have you ever taken a cooking class?",
                "What’s the best dessert in the world?",
                "How adventurous are you with trying new foods?",
            ],
            "hobbies" => [
                "What hobby have you always wanted to try but never did?",
                "What’s your favorite way to unwind after a long day?",
                "Do you prefer creative hobbies or physical ones?",
                "What hobby do you lose track of time doing?",
                "Have you ever turned a hobby into a side hustle or career?",
                "What’s a childhood hobby you still enjoy today?",
                "Do you prefer hobbies you do alone or with others?",
                "What’s the most unusual hobby you've encountered?",
                "What hobby would you recommend to someone looking to relax?",
                "What hobby did you pick up during the pandemic?",
                "Have you ever entered a competition for your hobby?",
                "What’s the most rewarding aspect of your hobby?",
                "How do you usually learn a new hobby — books, videos, classes?",
                "What’s a hobby that surprised you in how much you enjoyed it?",
                "Is there a hobby you’d like to teach others?",
                "Do your hobbies reflect your personality?",
                "What hobby do you think more people should try?",
                "How do you make time for your hobbies?",
                "Have your hobbies changed over time?",
                "What’s a simple hobby that brings you a lot of joy?",
            ],
            "pets" => [
                "Are you more of a cat person or a dog person?",
                "What’s the funniest thing your pet has ever done?",
                "Have you ever adopted a pet?",
                "Do you think pets understand us emotionally?",
                "What’s your dream pet and why?",
                "How do pets make life better?",
                "What’s the best pet name you’ve ever heard?",
                "Have you ever trained a pet to do tricks?",
                "What’s your favorite memory with a pet?",
                "Do you think owning a pet teaches responsibility?",
                "What exotic pet would you consider owning?",
                "How do you celebrate your pet’s birthday or milestones?",
                "What advice would you give a first-time pet owner?",
                "Have you ever had to care for a sick pet?",
                "What’s the most loyal thing your pet has done?",
                "Do you think pets have their own personalities?",
                "How do you choose names for your pets?",
                "What’s your opinion on pet fashion or accessories?",
                "Have you ever been surprised by a pet’s behavior?",
                "What’s something every pet owner should know?",
            ],
            "life_advice" => [
                "What’s the best advice you’ve ever received?",
                "What life lesson took you the longest to learn?",
                "How do you define success?",
                "What advice would you give your younger self?",
                "How do you handle failure or rejection?",
                "What’s a simple truth that’s helped you the most?",
                "How do you stay grounded during stressful times?",
                "Do you believe everything happens for a reason?",
                "What’s a mindset that changed your life?",
                "What role does gratitude play in your life?",
                "What’s one thing you try to live by every day?",
                "How do you maintain balance in life?",
                "What’s a habit that improved your life?",
                "What’s your personal mantra or motto?",
                "What’s something you wish more people understood?",
                "What’s the best way to build self-confidence?",
                "How do you make tough decisions?",
                "What’s your approach to personal growth?",
                "What’s the kindest thing you’ve done for yourself?",
                "What do you think makes a good life?",
            ],
            "tech_talk" => [
                "What piece of tech has changed your daily life the most?",
                "Are you more of an iOS or Android person?",
                "What’s the most underrated tech innovation?",
                "How do you stay updated with new technology?",
                "What’s your favorite productivity tool or app?",
                "Which tech trend are you most excited about?",
                "What’s a gadget you can’t live without?",
                "What’s your take on AI and the future of jobs?",
                "Are smart homes a good idea or too invasive?",
                "What’s a piece of outdated tech you still love?",
                "How do you protect your digital privacy?",
                "What’s your favorite tech brand and why?",
                "What’s your opinion on social media algorithms?",
                "Do you prefer cloud-based or local storage?",
                "What’s your biggest tech frustration?",
                "Do you think tech is making us more productive or distracted?",
                "What app do you use the most?",
                "What’s one tech skill you’d love to learn?",
                "What’s your opinion on wearable tech?",
                "How do you balance screen time in your life?",
            ],
            "gaming" => [
                "What was the first game you ever played?",
                "Do you prefer solo games or multiplayer experiences?",
                "What game world would you live in if you could?",
                "What’s the most emotionally impactful game you’ve played?",
                "What game do you never get tired of?",
                "How has gaming influenced your creativity or thinking?",
                "What’s your favorite game soundtrack?",
                "Are you a console or PC gamer?",
                "What’s the most challenging game you’ve beaten?",
                "Do you follow any streamers or esports?",
                "What’s your favorite co-op game?",
                "How do you feel about microtransactions in games?",
                "What game do you recommend to everyone?",
                "Have you ever made friends through gaming?",
                "What game character do you relate to most?",
                "What’s your guilty pleasure game?",
                "What’s a gaming moment you’ll never forget?",
                "Do you prefer story-driven games or action-packed ones?",
                "What upcoming game are you most excited for?",
                "Have you ever built or modded your own game content?",
            ],
            "couples" => [
                "What was your first impression of your partner?",
                "How do you show love in everyday life?",
                "What’s a favorite memory you share as a couple?",
                "How do you resolve conflicts together?",
                "What’s your favorite date you’ve been on?",
                "What’s a silly habit your partner has that you love?",
                "What does a perfect weekend together look like?",
                "How do you keep the romance alive?",
                "What are your relationship goals for the future?",
                "How do you support each other during tough times?",
                "What’s something new you’d like to try as a couple?",
                "What values do you both share?",
                "What’s a dream trip you’d love to take together?",
                "How do you celebrate milestones together?",
                "What’s your love language and how does your partner express it?",
                "How do you make each other laugh?",
                "What’s a tradition you’ve created as a couple?",
                "How do you handle time apart?",
                "What song best represents your relationship?",
                "What advice would you give to a new couple?",
            ],
            "family" => [
                "What’s your favorite family tradition?",
                "Who in your family inspires you the most?",
                "What’s a family recipe that’s been passed down?",
                "What’s the funniest thing that ever happened at a family gathering?",
                "What does your ideal family vacation look like?",
                "How do you stay connected with extended family?",
                "What’s one thing your family always does together?",
                "What role do you usually take in your family?",
                "How does your family celebrate holidays?",
                "What’s a value your family holds strongly?",
                "What do you admire about your parents or grandparents?",
                "How does your family support each other?",
                "What’s a story your family tells over and over again?",
                "What’s your earliest family memory?",
                "Do you have any family traditions you want to start?",
                "What’s something you’ve learned from a sibling?",
                "How do you handle disagreements in your family?",
                "What’s a typical family meal like for you?",
                "What’s the best thing about your family?",
                "How has your family shaped who you are today?",
            ],
            "work" => [
                "What was your very first job and what did you learn from it?",
                "Do you enjoy working in a team or independently?",
                "What’s your dream job?",
                "How do you stay motivated at work?",
                "What’s the best career advice you’ve ever received?",
                "How do you manage work-life balance?",
                "What’s the most challenging part of your job?",
                "Have you ever changed careers? What inspired the change?",
                "What’s a professional skill you’re proud of?",
                "How do you deal with work stress?",
                "What’s your typical workday like?",
                "What role does mentorship play in your career?",
                "What’s a big career goal you’re working toward?",
                "How do you stay organized and productive?",
                "What’s a workplace value you stand by?",
                "What’s one thing you wish more people understood about your job?",
                "What’s a memorable moment from your work life?",
                "How do you celebrate work accomplishments?",
                "What’s something new you’ve learned on the job recently?",
                "How do you approach feedback and growth?",
            ],
            "education" => [
                "What subject did you enjoy the most in school?",
                "How do you prefer to learn — by reading, doing, or listening?",
                "What teacher made the biggest impact on you?",
                "What’s a valuable lesson you learned outside the classroom?",
                "How do you stay curious and keep learning as an adult?",
                "What’s a course you’d love to take?",
                "How important is formal education to you?",
                "What’s a learning goal you’ve set for yourself?",
                "How do you overcome challenges in learning something new?",
                "What book changed your perspective on something?",
                "What role does education play in your personal growth?",
                "Do you enjoy structured learning or self-directed study?",
                "What’s one thing you wish schools taught?",
                "How do you apply what you’ve learned in real life?",
                "What’s a topic you could teach others about?",
                "What’s a skill you’ve taught yourself?",
                "What’s the most interesting thing you’ve learned recently?",
                "How do you stay disciplined when learning something difficult?",
                "Who inspires you to keep learning?",
                "How do you celebrate educational milestones?",
            ],

            "health_wellness" => [
                "What’s your go-to way to relax and de-stress?",
                "How do you prioritize your mental health?",
                "What does a healthy lifestyle look like for you?",
                "What’s your favorite form of exercise?",
                "How do you stay motivated to maintain good habits?",
                "What’s a wellness practice you swear by?",
                "How do you manage stress in tough times?",
                "What’s your relationship with food like?",
                "What’s one small change that improved your wellbeing?",
                "How do you recharge after burnout?",
                "What role does sleep play in your health routine?",
                "How do you practice mindfulness?",
                "What’s a myth about health you’ve learned to question?",
                "How do you support your emotional wellbeing?",
                "What’s a wellness goal you're working on?",
                "How do you balance productivity with rest?",
                "What’s your favorite healthy meal or snack?",
                "How has your view of health changed over time?",
                "What motivates you to take care of your body?",
                "What’s your favorite self-care activity?"
            ],
            "fashion" => [
                "What’s your favorite fashion trend right now?",
                "How would you describe your personal style?",
                "What’s your go-to outfit for feeling confident?",
                "Do you follow fashion trends or set your own?",
                "What’s a fashion risk you’ve taken?",
                "Who is your fashion icon?",
                "What’s your favorite accessory and why?",
                "How do you decide what to wear for a big event?",
                "What color do you wear the most and why?",
                "How has your style evolved over the years?",
                "What’s your favorite season to dress for?",
                "Do you prefer comfort or style?",
                "What’s one item in your closet you can’t live without?",
                "How do you organize your wardrobe?",
                "What’s a fashion piece you’ve always wanted?",
                "How do you express yourself through clothing?",
                "What do you think makes an outfit stylish?",
                "What’s your favorite thrift store or brand?",
                "Do you enjoy shopping for clothes?",
                "How do you feel about sustainable fashion?",
                "What’s a fashion trend you hope comes back?"
            ],
            "art_design" => [
                "What’s your favorite form of art?",
                "Who is your favorite artist and why?",
                "What inspires your creativity?",
                "How do you express yourself through art or design?",
                "What’s a piece of art that moved you deeply?",
                "What’s your favorite medium to work with?",
                "Do you prefer traditional or digital art?",
                "How do you stay inspired for creative projects?",
                "What’s your creative process like?",
                "How do you overcome creative blocks?",
                "What role does art play in your daily life?",
                "What’s a design style you love?",
                "How do you curate your living space with design?",
                "What’s a project you’re proud of?",
                "What’s your favorite museum or gallery experience?",
                "How do you learn or improve your artistic skills?",
                "What does beauty mean to you in design?",
                "How do you balance function and style in your work?",
                "What’s an art form you’d love to learn more about?",
                "How does art help you connect with others?"
            ],
            "history" => [
                "What historical figure do you admire most?",
                "What’s a historical event you wish you could witness?",
                "What era of history fascinates you the most?",
                "How does history shape the present?",
                "What’s a piece of history that’s often overlooked?",
                "Do you enjoy visiting historical landmarks?",
                "What’s a book or movie that taught you a lot about history?",
                "Who’s an unsung hero from history that inspires you?",
                "What lesson from history still applies today?",
                "How do you think history should be taught in schools?",
                "What’s a controversial event in history you’ve studied?",
                "What’s a personal connection you have to history?",
                "How do you verify historical information?",
                "What’s a tradition from the past you admire and why?",
                "If you could interview anyone from history, who would it be and why?",
                "What’s a historic place you’d love to visit and why?",
                "What’s a historical invention that changed the world for the better?",
                "What’s a mystery from history you wish were solved?",
                "How do you engage with history in your free time?",
                "What’s a historical myth or misconception you’ve debunked?"
            ],
            "science" => [
                "What scientific discovery amazes you most?",
                "What’s your favorite branch of science and why?",
                "How do you stay curious about the world around you?",
                "What’s a science experiment you remember doing as a child?",
                "What invention had the biggest impact on society, in your opinion?",
                "Who is your favorite scientist and why?",
                "What role does science play in your everyday life?",
                "What’s a recent scientific breakthrough that excites you?",
                "What’s a concept in science you’d like to understand better?",
                "How do you keep up with scientific news and discoveries?",
                "What’s your favorite science-related documentary or book?",
                "What’s something you’ve learned recently that surprised you?",
                "How do science and art intersect for you personally?",
                "What’s a natural phenomenon that fascinates you the most?",
                "How do you think science will shape the future of humanity?",
                "What’s your opinion on space exploration and its importance?",
                "What’s a common science myth you’ve debunked for yourself or others?",
                "How can science help solve today’s biggest problems, like climate change or health crises?",
                "What’s a cool fact about the universe that you love sharing with others?",
                "If you could ask a scientist any question, what would it be?"
            ],
            'developer' => [
                "What’s your favorite programming language and why?",
                "How do you handle debugging a tricky issue?",
                "What’s the most challenging project you’ve worked on?",
                "Do you prefer front-end or back-end development?",
                "What’s your go-to resource for learning new tech?",
                "How do you stay updated with industry trends?",
                "What’s a coding practice you swear by?",
                "Have you ever contributed to open source? If so, what?",
                "What’s your favorite development tool or IDE?",
                "How do you approach code reviews?",
                "What’s the most satisfying bug fix you’ve ever made?",
                "Do you prefer working solo or in a team?",
                "What’s a common misconception about developers?",
                "How do you manage work-life balance as a developer?",
                "What’s your favorite tech conference or event?",
                "If you could automate one part of your job, what would it be?",
                "What’s the best piece of advice you've received as a developer?",
                "How do you handle tight deadlines in development projects?",
                "What’s your favorite side project you've worked on?",
                "If you could learn any new technology instantly, what would it be?",
            ],
            "fx_designer" => [
                "What’s your go-to software for FX design and why?",
                "Practical effects or CGI — which do you prefer and when?",
                "Describe a moment when a simulation surprised you.",
                "What’s one FX shot you're especially proud of?",
                "How do you stay creative under tight deadlines?",
                "What's the most technically challenging effect you've worked on?",
                "What do you think makes an FX shot believable?",
                "What are your favorite FX-heavy films or games?",
                "Have you ever had an FX shot fail spectacularly? What happened?",
                "Which part of the FX pipeline excites you the most?",
                "What’s a tool or plugin you can’t live without?",
                "How do you keep up with industry trends and techniques?",
                "What’s the weirdest reference you've used for an effect?",
                "Do you prefer working in film, TV, games, or ads?",
                "What’s your approach to balancing realism and style?",
                "Share a tip for optimizing heavy FX scenes.",
                "What’s an overlooked skill every FX artist should develop?",
                "What’s your dream FX project or studio to work with?",
                "What makes a strong FX showreel stand out?",
                "How do you handle creative feedback or changes?",
            ],

        ];
        /* */
        foreach ($cards as $categoryKey => $questions) {
            /** @var Category $category */
            $category = $this->getReference('category_' . $categoryKey, Category::class);

            foreach ($questions as $question) {
                $card = new Cards();
                $card->setTitle($question);
                $card->setDescription(''); // or a brief explanation if needed
                $card->setCategoryId($category);

                $manager->persist($card);
            }
        }

        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            CategoryFixtures::class,
        ];
    }
}

/*


*/